SELECT P_NO, P_NAME,
TO_CHAR(TO_DATE(P_BIRTH, 'YYYYMMDD'), 'YYYY"년"MM"월"DD"일"') P_BIRTH,
CASE P_GNEDER WHEN 'M' THEN '남' WHEN 'F' THEN '여' END P_GNEDER,
P_TEL1 || '-' || P_TEL2 || '-' || P_TEL3 P_TEL,
CASE P_CITY WHEN '10' THEN '서울' WHEN '20' THEN '경기' WHEN '30' THEN '강원' WHEN '40' THEN '대구' END P_CITY
FROM TBL_PATIENT_202004;

INSERT INTO TBL_RESULT_202004 VALUES
(?,?,?,?,?,?);

SELECT R.P_NO, P.P_NAME,L.T_NAME, 
TO_CHAR(R.T_SDATE, 'YYYY-MM-DD') T_SDATE,
CASE R.T_STATUS WHEN '1' THEN '검사중' WHEN '2' THEN '검사완료' END T_STATUS,
TO_CHAR(R.T_LDATE, 'YYYY-MM-DD') T_LDATE, 
CASE R.T_RESULT WHEN 'X' THEN '미입력' WHEN 'P' THEN '양성' WHEN 'N' THEN '음성' END T_STATUS_RESULT
FROM TBL_RESULT_202004 R
JOIN TBL_PATIENT_202004 P ON P.P_NO = R.P_NO
JOIN TBL_LAB_TEST_202004 L ON L.T_CODE = R.T_CODE
ORDER BY R.P_NO;

SELECT P.P_CITY,
CASE P.P_CITY
	WHEN '10' THEN '서울'
	WHEN '20' THEN '경기'
	WHEN '30' THEN '강원'
	WHEN '40' THEN '대구'
END CITY_NAME,
COUNT(T.P_NO)
FROM TBL_PATIENT_202004 P
JOIN TBL_RESULT_202004 T ON P.P_NO = T.P_NO
GROUP BY P.P_CITY;

